messages:
  help: 'Ваша команда введена не правильно, /texpbottle <amount/reload>.'
  only-player: 'Команда только для игроков.'
  no-perm: 'У вас недостаточно прав.'
  exist-exp: 'Ваше введенное значение уровня нету в списке.'
  reload: 'Конфигурация &aуспешно&f перезапущена.'
  small-level: 'Ваше значение уровня ниже того, что вы ввели.'
  success-give: 'Вам успешно выдали бутылёк с уровнем: %level%.'

#Право на использование texpbottle.use
exp-bottle-settings:
  name: 'Пузырёк с говном в количестве %level%.'
  lore:
    - 'Введи, что хочешь.'
    - 'Опыта тут много, аж %level%.'
  flags: #Флаги для твоего пузырька, смотри, чтобы такие существовали.
    - 'HIDE_ENCHANTS'


max-exp:
  - '15'
  - '30'